import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import SessionProvider from "@/providers/SessionProvider";
import Navbar from "@/components/navbar/Navbar";
import { cn } from "@/lib/utils";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-dvh bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <SessionProvider>
          <Toaster richColors position="top-center" />
          <Navbar />
          <main className="mx-auto max-w-screen-xl px-4">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
